"""
Django settings for centromedico project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from decouple import config
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent 


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
FERNET_KEY = config('FERNET_KEY')
FIELD_ENCRYPTION_KEY = config('ENCRYPTED_MODEL_FIELDS_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG')

ALLOWED_HOSTS = ['centromedicoimmune.onrender.com', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cryptography',
    'django_extensions',
    'centroimmune',
    'corsheaders',
    'csp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files efficiently
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'centroimmune.middlewares.CSPNonceMiddleware',  # Add this line
]



ROOT_URLCONF = 'centromedico.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'centromedico.wsgi.application'

AUTH_USER_MODEL = 'centroimmune.User'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL')
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'  # Change this to your desired timezone

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    STATICFILES_DIRS = [BASE_DIR / 'centroimmune' / 'static']
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRYPTOGRAPHY_KEY = config('CRYPTOGRAPHY_KEY')


# Content Security Policy (CSP)
CSP_DEFAULT_SRC = ("'self'",)  # Only allow resources from the same origin

# More restrictive script policy (remove 'unsafe-inline')
CSP_SCRIPT_SRC = ("'self'", "https://cdnjs.cloudflare.com", "https://cdn.jsdelivr.net", "https://leostop.com","'strict-dynamic'")

# Allow styles from self and Google Fonts (limit 'unsafe-inline' use)
CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com", "'unsafe-inline'")

# Restrict object-src to none for security
CSP_OBJECT_SRC = ("'none'",)

# Prevent base tag injections
CSP_BASE_URI = ("'self'",)

# Font sources (restrict data: URIs if not required)
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "data:")

# Image sources (restrict data: URIs if not needed)
CSP_IMG_SRC = ("'self'", "data:")

# Allow only self for AJAX and WebSocket connections
CSP_CONNECT_SRC = ("'self'",)

from django.utils.crypto import get_random_string

# Security settings
SESSION_COOKIE_SECURE = True  # Ensures cookies are only sent over HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript from accessing the session cookie
X_FRAME_OPTIONS = 'DENY'  # Prevents your site from being loaded in an iframe
CSRF_COOKIE_SECURE = True  # Ensures CSRF cookie is only sent over HTTPS
CSRF_COOKIE_HTTPONLY = True  # <-- Add this line

# Set session timeout to 10 min
SESSION_COOKIE_AGE = 600  # 10 minutes

# Expire session at browser close
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Save session after every request
SESSION_SAVE_EVERY_REQUEST = True

SECURE_REFERRER_POLICY = 'same-origin'


# Email Configuration using Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Your Gmail app password (or regular password)
DEFAULT_FROM_EMAIL = 'Centro Medico Inmune <urboventures@gmail.com>'

# Usar HTTPS (TLS/SSL)
# https://docs.djangoproject.com/en/stable/ref/middleware/#module-django.middleware.security
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Protege contra clickjacking
X_FRAME_OPTIONS = 'DENY'

# Protección contra ataques XSS
SECURE_BROWSER_XSS_FILTER = True

#Esto es solo en entorno de preproducción
CORS_ALLOW_ALL_ORIGINS = True

#Aquí hay que meter las URL de las API que usemos
CORS_ALLOWED_ORIGINS = [

]
