# Generated by Django 5.0.2 on 2024-09-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centroimmune', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
