# Generated by Django 5.0.2 on 2024-09-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroimmune', '0003_alter_cita_tratamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='duracion',
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CategoriaTratamiento',
        ),
    ]
